name: app
description: "Fingerprint App"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3
dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.17
  google_fonts: ^6.2.1
  intl: ^0.19.0
  location: ^5.0.3
  mapbox_maps_flutter: ^2.8.0
  permission_handler: ^11.3.0
  provider: ^6.1.4
  salomon_bottom_bar: ^3.3.2
  shared_preferences: ^2.5.3
  socket_io_client: ^2.0.1
  url_launcher: ^6.2.5
  cached_network_image: ^3.4.1
  dio: ^5.8.0+1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
